### ISSUE TITLE
Chocolatey package

### ISSUE THREAD

**Issue by h0ek** [tristanheaven/gtkhash#101]
Hi,

I created Chocolatey package for GtkHash.
[https://chocolatey.org/packages/gtkhash/](https://chocolatey.org/packages/gtkhash/)

Maybe it will be useful for someone.

**Comment by tristanheaven** [comment]
Thanks, @h0ek! Let me know if there's something I should do to improve the Windows installer.

**Comment by h0ek** [comment]
Yeah sure. For now everything works great. No problem at all.
Thanks for your great program.
