### ISSUE TITLE
for langguage indonesia

### ISSUE THREAD

**Issue by dnandz** [tristanheaven/gtkhash#105]
if you have question for translate or the translate going wrong in bahasa langguage contact me..
sorry my english not so good , but i know learning by doing :+1: 
if another developer need my help my pleasure i will help as fast as i can....

**Comment by tristanheaven** [comment]
Thanks @dnandz. I've merged your changes.

**Comment by dnandz** [comment]
> Thanks @dnandz. I've merged your changes.
ok mate... my pleasure
