### ISSUE TITLE
Windows binary?

### ISSUE THREAD

**Issue by nazibalalam** [tristanheaven/gtkhash#112]
Hey! Just wanted a binary available for windows, or just the build instructions

**Comment by tristanheaven** [comment]
Hi @nazibalalam. There are 32-bit and 64-bit installer and zip files for the latest version on the [releases page](https://github.com/tristanheaven/gtkhash/releases), and for every commit on [AppVeyor](https://ci.appveyor.com/project/tristanheaven/gtkhash/build/artifacts).

There's also a Chocolatey package you could try (#101).

If you want to build from source, it can be done using [MSYS2](https://www.msys2.org/). The build scripts are in the msys2 directory in this repo.

**Comment by nazibalalam** [comment]
Thank you very much! I just forgot to expand the "assets" part, and just saw the snap store icon... I'll try to contribute to this project!

**Comment by nazibalalam** [comment]
You can close this now...
