### ISSUE TITLE
Feature request: folder recursivity ?

### ISSUE THREAD

**Issue by sviscapi** [tristanheaven/gtkhash#123]
Dear @tristanheaven ,

If I'm not mistaken, in order to compute several checksums at once, one has to go to "View" / "Files list" and then click on the "Add" button to select the files.

Could you please add folder recursivity to gtkhash to make this process easier ?

Best regards,

Samuel

**Comment by tristanheaven** [comment]
Yes, that's been "to do" for a long time.

**Comment by sviscapi** [comment]
Hi @tristanheaven ,

Do you think you could add this feature in time for the next 1.5 release ?

If you need some beta testers, you know where to find me ;)

Best regards,

Samuel

**Comment by sviscapi** [comment]
Dear @tristanheaven ,

Would you have any news regarding this issue ?

If you implement this functionality I believe I could build the new version at home (Debian 11 x86_64) and give you some feedback, but the main users I have in mind will use the Windows version at work.

Best regards,

Samuel

**Comment by sviscapi** [comment]
Dear @tristanheaven ,

Just to let you know that GTKHash could be used by a large French administration **if** that folder recursivity feature is implemented ;)

Best regards,

Samuel

**Comment by tristanheaven** [comment]
If that's the only requirement, why doesn't a large French administration contribute the code for it?

As it happens, I might have some time to look at it soon, but the current priority is to fix the Windows build.

**Comment by sviscapi** [comment]
Dear @tristanheaven ,

As an FSF member, I totally get your point :) Unfortunately we don't have many developers around, and I'm a system administrator by trade, so I doubt I could contribute anything valuable to your code.

I'm closing this issue and won't bother you anymore with it.

Best regards,

Samuel
