### ISSUE TITLE
How to enable: Whirlpool & Tiger ?

### ISSUE THREAD

**Issue by Sanyy** [tristanheaven/gtkhash#13]
With the description i could enable SHA3 & Blake2 but there is no whirlpool&tiger.
Which libraries are required for those?

or were they already removed and [this site](http://gtkhash.sourceforge.net/) was not updated?

thx

**Comment by tristanheaven** [comment]
Hi,

For whirlpool and tiger192, I'd recommend --enable-gcrypt . 

Or for a minimal install, you might be able to use the Linux kernel crypto hash api. --enable-linux-crypto will enable detection of the kernel interface and algorithms.
