### ISSUE TITLE
GtkHash (warning?) Message.

### ISSUE THREAD

**Issue by Achaean** [tristanheaven/gtkhash#133]
**Hi!**  :-)

I just compiled and installed locally (on a Debian based system), the last GTKHash version.

Everything went smooth and it operates flawlessly.
Only thing I'm reporting, is this warning message, everytime it starts (from console).

**Note:** Since I don't need all the provided options, (at config time) I kept the linux kernel option and disabled all the rest.
(With this command: ./configure --disable-blake2 --disable-internal-md6 --disable-zlib --disable-gcrypt --enable-linux-crypto).

And here's the startup warning:
```
>gtkhash
GtkHash-Message: Kernel AF_ALG 'sha3-224': No such file or directory
GtkHash-Message: Kernel AF_ALG 'sha3-256': No such file or directory
GtkHash-Message: Kernel AF_ALG 'sha3-384': No such file or directory
GtkHash-Message: Kernel AF_ALG 'sha3-512': No such file or directory
GtkHash-Message: Kernel AF_ALG 'blake2b-512': No such file or directory
GtkHash-Message: Kernel AF_ALG 'blake2s-256': No such file or directory
>
```

**Comment by tristanheaven** [comment]
I agree those messages aren't very useful. They're now hidden unless `G_MESSAGES_DEBUG=GtkHash` is set.

Thanks.
