### ISSUE TITLE
Preferences aren't saved.

### ISSUE THREAD

**Issue by Achaean** [tristanheaven/gtkhash#15]
Preferences are lost when closing GTKHash.
When launching GTKHash, you have to configure them again.

I have latest version (1.1), on Debian Jessie (oldstable) x64 KDE.

**Comment by tristanheaven** [comment]
It's fixed in 7d94836c0169585f838c1f88b6f44db87c355b5e, but I still need to do a new release.

Thanks for the reminder.

**Comment by Achaean** [comment]
**THANKS** Tristan!!! ;-)
