### ISSUE TITLE
Building problem.

### ISSUE THREAD

**Issue by Achaean** [tristanheaven/gtkhash#16]
**Hi!** :-)

Which is the proper way to build the last gtkhash version?
I ran into some problems with the last version, so here I am! :-)

First things first.
It confuses me the autogen script.
Do I have to run autogen.sh or configure;make;make install?
**TIA!** :-)
A.

**Comment by tristanheaven** [comment]
Hi,

You'll only need to run autogen.sh if you're building from a git clone. If you have one of the release archives (tar.gz or tar.xz), the generated files are already there. This will reduce the number of build-time dependencies, and you can go straight to running configure and then make.

https://github.com/tristanheaven/gtkhash/releases

Thanks,

Tristan

**Comment by Achaean** [comment]
**THANKS** Tristan!!! :-)

PS. Meanwhile, I found the answers to the rest 2 installation problems.
I'm posting them, just in case who someone (Debian based ?) stumble  upon them.

1) Make check failed, but it's related to a bug (supposedly not present on newer systems).
https://bugs.launchpad.net/ubuntu/+source/at-spi2-core/+bug/1217757
Being on Debian Jessie (oldstable), affects me. Nothing to worry about.

2) Initially configuration failed, informing that libgcrypt not found.
Installing the newer version from backports, solved the problem.

**THANKS AGAIN!!!** :-)
A.
