### ISSUE TITLE
1.1.1 release does not build with Ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by josephpaul0** [tristanheaven/gtkhash#17]
checking for LIBGCRYPT - version >= 1.7.0... no

Are aware that /usr/bin/libgcrypt-config --version = 1.6.5 on Ubuntu 16.04 ?

**Comment by tristanheaven** [comment]
I wasn't aware. It's a bit late to fix this now (new LTS is coming), but I'll check available LTS versions before adjusting dependencies like that in future.

As gcrypt is only an optional dependency anyway, you might be able to use nettle instead to provide mostly the same functionality:

./configure --disable-gcrypt --enable-nettle

**Comment by tristanheaven** [comment]
I had to find a way to avoid adding a new dependency on 1.8.0, so I've used the same method to drop the required version to 1.6.0 now.

Thanks.
