### ISSUE TITLE
./configure --prefix=$HOME/opt  tries to install in /usr/lib

### ISSUE THREAD

**Issue by josephpaul0** [tristanheaven/gtkhash#18]
On LinuxMint 18 MATE:
./configure --prefix=$HOME/opt --enable-linux-crypto --enable-caja --disable-gcrypt --enable-nettle  --enable-mhash --enable-mbedtls

make

/usr/bin/install: cannot create regular file '/usr/lib/x86_64-linux-gnu/caja/extensions-2.0/libgtkhash-properties-caja.so': Permission denied

**Comment by tristanheaven** [comment]
It's not really a bug. The installation path is defined by caja itself:

pkg-config --variable=extensiondir libcaja-extension

It wouldn't make sense to install the extension anywhere else as caja wouldn't load it. That is unless caja supports loading extensions from ~/.local or similar. In which case, I'd be interested in adding an option to install it there.

If you're intending to just install to ~/opt without running from there, you'd be better off trying something like:

**Comment by tristanheaven** [comment]
make DESTDIR=~/opt
