### ISSUE TITLE
save hash result in UTF-8

### ISSUE THREAD

**Issue by qwerty258** [tristanheaven/gtkhash#19]
This is a handy GUI program but when file name has non-ASCII characters, it saves hash result in URL encoding format which is not compatible with `md5sum`, `sha1sum`, `sha256sum`.

**Comment by tristanheaven** [comment]
I haven't found a problem with the filename encoding in saved files so far. Is it a local file or remote?

Could you give an example filename which is encoded differently to md5sum output?

Thanks

**Comment by qwerty258** [comment]
GtkHash 0.7.0 Ubuntu 16.04.3
file name: `测试测试.txt`
file content: `测试测试`
```
$ md5sum 测试测试.txt 
57d06e427361f6fd0356fe5f2a665f2b  测试测试.txt
```
```
$ cat GtkhashResult.txt 
# MD5
57d06e427361f6fd0356fe5f2a665f2b  %E6%B5%8B%E8%AF%95%E6%B5%8B%E8%AF%95.txt
# SHA1
cea019ba1989ef779d2be1203482ecf73de543c6  %E6%B5%8B%E8%AF%95%E6%B5%8B%E8%AF%95.txt
# SHA256
f401864493f508c668c1aa2c620651630044712f5742509504d79e44c0965269  %E6%B5%8B%E8%AF%95%E6%B5%8B%E8%AF%95.txt
```
Maybe the version is too low ...
