### ISSUE TITLE
nautilus part not translated

### ISSUE THREAD

**Issue by tuxmaster** [tristanheaven/gtkhash#20]
In the nautilus plug-in the translations looks missing.
On an German system the dialogue  are shown in English.
![bildschirmfoto von 2018-04-02 10-31-05](https://user-images.githubusercontent.com/6240474/38189537-051b4e2e-3661-11e8-938f-154bc382b302.png)
The text shout display as followed:
Check -> Prüfen
Digest(menu bar) -> Prüfsummen
Digest(table) -> Prüfsumme
Hash(button) -> Berechnen
Stopp -> Abbrechen

Context menu:
Copy Digest -> Prüfsumme kopieren
Show Disabled Hash Functions -> Deaktivierte Algorithmen anzeigen

**Comment by tristanheaven** [comment]
It looks like you have quite an old version. Here's a screenshot from 1.1.1:

![de_de](https://user-images.githubusercontent.com/26687/38197883-e1485bd6-3679-11e8-9a09-ea4977dd1459.png)

I include any translation changes from Weblate in each release, so feel free to send improvements there (you can login with your GitHub account):

https://hosted.weblate.org/translate/gtkhash/translations/de/

Thanks
