### ISSUE TITLE
Thunarx-3 port

### ISSUE THREAD

**Issue by andreldm** [tristanheaven/gtkhash#21]
Hello there,
I am of the Thunar current maintainers and am getting in touch to let you know that we released 1.7.x a while ago. It features a new version of the Thunar Extensions API, which is compatible with GTK3. Even though Thunar 1.7.x is a series of development releases, the API is stable and hasn't changed much, more details here:
https://wiki.xfce.org/releng/4.14/roadmap/thunar/thunarx-cleanup

Thunar 1.8.0 (stable) is to be release in the next months, so I believe it would be great to have gtkhash available to our users by that time.

**Comment by tristanheaven** [comment]
Thanks. I've added a configure option for that, defaulting to thunarx-3.

**Comment by andreldm** [comment]
Many thanks for your prompt response.
