### ISSUE TITLE
Failure to build with newer versions of thunar

### ISSUE THREAD

**Issue by GIJack** [tristanheaven/gtkhash#22]
$ pacman -Q thunar
thunar 1.8.1.11.gf5147445-1

configure: error: Package requirements (thunarx-2) were not met:

Package 'thunarx-2', required by 'virtual:world', not found

jack@titanium:~$ pacman -Ql thunar|grep thunarx
thunar /usr/include/thunarx-3/
thunar /usr/include/thunarx-3/thunarx/

**Comment by tristanheaven** [comment]
Fixed in v1.2, thanks.
