### ISSUE TITLE
Blake 2 h file not found.

### ISSUE THREAD

**Issue by Achaean** [tristanheaven/gtkhash#23]
**Hi!** :-)

I just tried to compile the stable version. The requirements are met I think, but the Blake2 source couldn't be found.
Installing blake2 binary from it's official page, didn't (obviously) help.

Here are the last lines of console's output:

```
checking blake2.h usability... no
checking blake2.h presence... no
checking for blake2.h... no
configure: error: blake2 header not found
>

```

**Comment by tristanheaven** [comment]
Hi,

blake2.h is from libb2 (https://github.com/BLAKE2/libb2), or a distro package (e.g. libb2-dev).

Alternatively, you can disable the dependency with the configure option --disable-blake2 .

Thanks,

Tristan

**Comment by Achaean** [comment]
Ooops! My fault. :-)
Libb2 it was also available at Devuan's repository.
It was only needed a Synaptic search for "blake", with the "name and description" option enabled.
I think I was in need of a brake at the time! :-)

**THANKS** Tristan!!!
