### ISSUE TITLE
Problem with nettle-3.5.1-1

### ISSUE THREAD

**Issue by anonymous133** [tristanheaven/gtkhash#29]
Hi Guys,

When I try to start gtkhash I get the following error:

gtkhash: error while loading shared libraries: libnettle.so.6: cannot open shared object file: No such file or directory

I can solve the issue, when I revert back via sudo pacman -U /var/cache/pacman/pkg/nettle-3.4.1-1-x86_64.pkg.tar.xz

but then I run into other software not functioning properly. 

I installed gtkhash from AUR. 

My system is up to date and I don't do partial upgrades nor have I pacman ignore packages.

Thank you!

**Comment by tristanheaven** [comment]
I think gtkhash is still API-compatible with the new version of nettle, even though the SONAME has changed. Rebuilding your AUR package should make it link against libnettle.so.7 instead. 

Maybe something like this:

makepkg --force --install

**Comment by anonymous133** [comment]
Thank you, it worked!
