### ISSUE TITLE
source string location are giving 404 errors

### ISSUE THREAD

**Issue by leela52452** [tristanheaven/gtkhash#30]
on weblate source strings are giving 404 errors.
see [source](https://hosted.weblate.org/projects/gtkhash/translations/source/review/?type=check%3Aellipsis)

**Comment by tristanheaven** [comment]
Thanks for reporting. I think there are two separate issues here:
1. The git branch name (master) is missing from all links
2. Some links are pointing to generated files which doesn't exist in the repo (e.g. xml.h)

I've asked Weblate for help with issue 1.

**Comment by tristanheaven** [comment]
Issue 1 should be fixed now. That covers strings from .c files.

**Comment by tristanheaven** [comment]
I think the second issue could be fixed by removing the intltool dependency.

https://wiki.gnome.org/MigratingFromIntltoolToGettext

**Comment by tristanheaven** [comment]
Source string links should all be working now.
Thanks
