### ISSUE TITLE
GTKhash scripting question

### ISSUE THREAD

**Issue by pclinuxer** [tristanheaven/gtkhash#36]
Not an issue, just a question please:
I am trying to get GTKhash to run from a script in Xfe.

```
#!/bin/sh
for arg
do
	gtkhash "$arg"
done
```
This sets the name of the file selected via a right click on the mouse but my script knowledge being poor, I am at odds as to how to run the instruction -Hash- after that so that it opens with all the hash functions selected in Edit -> Preferences already calculated.   

Thanks in advance,
PCL

**Comment by pclinuxer** [comment]
Figured it out.

```
for arg
do
	gtkhash "$arg" -t "$arg"
done
```
Works perfectly in X File Explorer 1.42.

PCL

**Comment by tristanheaven** [comment]
If you want to open multiple files in the same window, I think you could do this:

```sh
#!/bin/sh
exec gtkhash -- "$@"
```

Thanks,

Tristan

**Comment by pclinuxer** [comment]
> If you want to open multiple files in the same window ... 
Thank you.
Best,
PCL

**Comment by pclinuxer** [comment]
> If you want to open multiple files in the same window ... 
Thank you.
Best,
PCL

**Comment by pclinuxer** [comment]
> 

>
