### ISSUE TITLE
No screenshots on README

### ISSUE THREAD

**Issue by fidergo-stephane-gourichon** [tristanheaven/gtkhash#38]
https://github.com/tristanheaven/gtkhash says 

> "GtkHash is a desktop utility for computing message digests or checksums."

People love screenshots and detailed feature list, to know what to expect before trying.

So I compiled the program and made a screenshot.

Suggestion to fix: add screenshot to README.md .

![gtkhash_preview](https://user-images.githubusercontent.com/2843528/71785526-e64a8c80-3000-11ea-9489-82b1d59bd459.png)

**Comment by tristanheaven** [comment]
Thanks, I've added your screenshot.

**Comment by fidergo-stephane-gourichon** [comment]
Happy to help.

That was quick!

> * File manager integration

Oh, so you can drag-n-drop?

Here's a screenshot.

![gtkhash_dragndrop](https://user-images.githubusercontent.com/2843528/71786983-26fed180-3012-11ea-8207-03e70d699294.png)

This allowed me to discover the "file list" view which I did not notice before.

![gtkhash_gridview](https://user-images.githubusercontent.com/2843528/71787001-439b0980-3012-11ea-9319-e63dddae66e6.png)
