### ISSUE TITLE
Multi-thread not always good

### ISSUE THREAD

**Issue by fidergo-stephane-gourichon** [tristanheaven/gtkhash#39]
From the README:

> * Parallel/multi-threaded hash calculation

On a CPU-starved machine this is good. When a fast CPU computes hashes from a mechanical (spinning platters) harddrive, multithread can be a performance killer: threads competing for the hard drive cause disk thrashing, dividing the performance by about 10-100.

This happened to me today I used `md5deep` to compute hashes of many files today (Xubuntu 19.10, 4-core 8-thread Intel, USB2-connected SATA hard drive). Performance was very poor (like 500kbytes/second) in multithread and hard drive noisy. Using `-j0` on md5sum it came back to a normal 20+Mbytes/s (which is typical of a USB-2 connected hard drive). The same can happen for other cable or storage attachment and is due to high latency when thread compete for hard drive head positioning. Kernel can be fine-tuned, but the truth is: multi-thread make no sense in that case.

Do you have a heuristics to detect if multi-thread is useful or performance killer? Perhaps at least warn the user?

Thank you anyway.

**Comment by tristanheaven** [comment]
Perhaps the README should be made clearer there. The file hashing is assumed to be CPU-bound, so it will run each algorithm in a separate thread (up to `nproc` threads). File reading is all done sequentially (one file at a time, in 128K chunks).

Currently it's not possible to control this threading without using some external tool. Hopefully it results in better performance for most people, without any need for configuration.

**Comment by tristanheaven** [comment]
I have thought about making the chunk size configurable at least, as it can make a significant difference to performance. Would be interested if you have any other ideas.

Thanks
