### ISSUE TITLE
Application icons

### ISSUE THREAD

**Issue by snowolfe** [tristanheaven/gtkhash#4]
There doesn't appear to be any associated application icon(s) - so I have put these together.

The README has the license details (CC-BY-SA 3.0) for the original and my modifications. Feel free to use them (or not).
[gtkhash3.zip](https://github.com/tristanheaven/gtkhash/files/102767/gtkhash3.zip)

**Comment by tristanheaven** [comment]
I'm not sure the "#" symbol really represents "hash" in this context. That said, I don't have any better ideas (or graphics skills), so I think I'll add this. Thanks.
