### ISSUE TITLE
Replace "Digest" word with "Checksum" in some places

### ISSUE THREAD

**Issue by nick87720z** [tristanheaven/gtkhash#40]
For now I mean only one place, where this word seems to me personally not enough lucky: file properties plugin, whose tab has just this word in name. I suspect it would need wider discussion with translators as well or anyone who could tell about other translations. I can tell only about russian as my essential.

I have thunar as primary fm (thanks to xfce), but by some reasons had to resort to pcmanfm for relatively long time. When I returned, and looked to properties of some file, I had... some short delay, trying to understand where is right tab, related to GtkHash.

Problem is that 'Digest' word, as well as its russian translation (just transliterated 'digest' transcription) has two meanings: one is hash sum, but second - like "summary", taking place in various PIM's, like KDE Kontact & KOrganizer combo.

Imho, two other variants - "Hash" and "Checksum" would be more precise. First may be best by length (at both languages), but somewhat professional term. Second - at russian translates to two separate words "Check Sum", but seems to be most understandable (I remember we learned first case at Economics lessons in school, while learned manual barcode validation).

**Comment by tristanheaven** [comment]
Agreed. I'll change it in the file properties tab name at least. That should make it clearer to most people what is in the tab, without needing to click to find out.

I've tried to use consistent naming so that Hash is verb, Digest/Checksum are noun (and equivalent). I'm not sure whether this has been followed in the translations though.
