### ISSUE TITLE
[Feature request] Add support for "base64" encoded

### ISSUE THREAD

**Issue by Nokia808** [tristanheaven/gtkhash#44]
Hi dear developer.
1st of all, I would like to give my thanks for this excellent application ......

Dear, I saw some sites & developers using "base64" encoded like this one (please examine AppImage file of version 2.0.2):
https://github.com/jitsi/jitsi-meet-electron/releases
&, kindly, read the issue that I'm already opened there:
https://github.com/jitsi/jitsi-meet-electron/issues/318

It will be very useful to add support for "hase64" encoded in your great application so that we can avoid command line & insecure sites like:
http://tomeko.net/online_tools/hex_to_base64.php

Thank you very much !

**Comment by tristanheaven** [comment]
I think that's already done. I checked the file and base64 sha512 value in GtkHash and it matched. You just have to select Base64 as the Digest Format in Preferences first. 

Thanks,
Tristan

**Comment by Nokia808** [comment]
@tristanheaven 
Yes, I saw it just when I read your replay! It was hidden from my eyes .... Thank you ! However, I discover during this a bug that I will post issue about it ....
