### ISSUE TITLE
GtkHash show system error when opened & closed without checking file !

### ISSUE THREAD

**Issue by Nokia808** [tristanheaven/gtkhash#47]
Hi dear developer. During my search to use base64 encoded as you command me at https://github.com/tristanheaven/gtkhash/issues/44 I discovered a bug:

GtkHash version 1.2 from my official Fedora 30 X64 bit repositories will show a system error if user just launch it then close it without hashing any file ! To reproduce this error do the following:

- launch program,
- not use it to select & hash any file,
- then close it.

Please try this. If you reproduce this bug then it is a bug in your application. If you could not reproduce it, then it is Fedora specific package bug & in the later case I should wait for 1 month before I upgraded from Fedora 30 to Fedora 32 to see if it will disappear or will remain ....

**Comment by tristanheaven** [comment]
That seems like the problem from before commit 237948d6f856431. I think it could be a bug in the rust version of librsvg, but I put in this workaround anyway. It's not included in a release yet.

Thanks

**Comment by tristanheaven** [comment]
Should be fixed in version 1.3. Please re-open if it still happens.

Thanks.
