### ISSUE TITLE
[feature] Separate buttons to start calculating the hash for every Hash function

### ISSUE THREAD

**Issue by j1warren** [tristanheaven/gtkhash#50]
Currently there's only one Hash button that starts calculating all the selected hashes.
If this one time I want only to see MD5 I either should calculate all of them (that I've selected as often needed) and wait, or go to settings, select only MD5, hash it, then go back and select all other hashes I often use.

If there would be an individual Hash button next to every Hash function in the list, it would help in such situation.

**Comment by tristanheaven** [comment]
Done for File view only. You can click the function name and it'll run without calculating the others, and without changing your preferences.

**Comment by j1warren** [comment]
Thank you, @tristanheaven!
One more thing, is it possible to implement the same functionality for nautilus/nemo extension?

**Comment by tristanheaven** [comment]
It's possible, but not in the same way. I think double click on a row could work.

**Comment by tristanheaven** [comment]
Added to file manager extensions. "Activating" a row (e.g. double click) will only run the selected function.

**Comment by j1warren** [comment]
Awesome, thank you, Tristan!
