### ISSUE TITLE
Crash on wrong allocation

### ISSUE THREAD

**Issue by nick87720z** [tristanheaven/gtkhash#6]
On attempt to calculate something (with any hash) it crashes with error:
`(gtkhash:475): GLib-ERROR **: /var/calculate/tmp/portage/dev-libs/glib-2.48.2/work/glib-2.48.2/glib/gmem.c:100: failed to allocate 18446744073709551615 bytes
`

**Comment by tristanheaven** [comment]
Are you able to provide a gdb backtrace? That'd probably help me figure out what's going on here. Thanks.

**Comment by tristanheaven** [comment]
Probably a bug related to using linux kernel crypto (--enable-linux-crypto configure option)
