### ISSUE TITLE
libcaja-extension missed on XFCE, installation failed

### ISSUE THREAD

**Issue by kzoli429** [tristanheaven/gtkhash#77]
I understand gtkhash (and gtkhash-thunar) is a package independent from Desktop Environment.
I use the latest version of Arch Linux with XFCE for which an installer package is available in AUR.
Either I try to update gtkhash v1.2-1 or do a fresh install I receive the following messages:
"
...
checking whether to build the Caja extension... yes
checking for CAJA... no
configure: error: Package requirements (libcaja-extension) were not met:

Package 'libcaja-extension', required by 'virtual:world', not found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables CAJA_CFLAGS
and CAJA_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
==> ERROR: A failure occurred in build().
    Aborting...
error making: %!s(func() string=0x5619447ed830)
"

Note: No caja package is installed.

**Comment by tristanheaven** [comment]
It looks like the recent 1.4-1 update in AUR would fix this. That version tries to detect your default file manager, so it shouldn't enable caja if you don't have it.

**Comment by kzoli429** [comment]
Unfortunately, 1.4-1 definitely suffers with the same error.

**Comment by kzoli429** [comment]
FYI: a reponse to the command "xdg-mime query default inode/directory" is "easytag.desktop" which is weird.
I'll try to find the reason for that and follow the way to rectify my installation issue.
Thank you for your efforts.

**Comment by tristanheaven** [comment]
Ah well it seemed like a nice idea but I guess that shows it's not very reliable. I'd suggest the AUR maintainer makes a separate package for each file manager if there's no better way to specify conditional dependencies in a PKGBUILD. I'm not an Arch user, otherwise I'd attempt it myself.

**Comment by kzoli429** [comment]
If the Easytag application for viewing and editing tags in audio files is installed, the file manager priority is changed from thunar.desktop to easytag.desktop. It may not be not evident for many Arch Linux users (why should be).
The simplest solution may be to overwrite inode/directory in ~/.local/share/applications/mimeapps.list
