### ISSUE TITLE
Requirements?

### ISSUE THREAD

**Issue by Achaean** [tristanheaven/gtkhash#8]
**Hi!** :-)
Any description, of the optional requirements?
What are they useful for?

I installed GTKHash on my Debian system (Jessie x64) and I didn't install any of them (although some of them were already present), and GTKHash seems to be fully functional.

**TIA!** :-)
G.

**EDIT:**
OK! ".configure" results are enlightening enough and they're providing these informations.
This thread can be closed.

PS. Intltool seems to be another requirement (at least at Debian systems).
Also XVFB, (only if you want to run "make check").

**Comment by tristanheaven** [comment]
All good
