### ISSUE TITLE
HMACs not produced with some algorithms

### ISSUE THREAD

**Issue by Ricky-Tigg** [tristanheaven/gtkhash#86]
**OS:** Fedora; **Component:** gtkhash.x86_64  1.4-1.fc32

_HMACs_ are not produced with those algorithms:

![GtkHash_v1 4_HMAC](https://user-images.githubusercontent.com/26058215/92444575-c4229300-f1bb-11ea-8942-5839c936b99e.png)

_HMACs_ are produced as intended with those algorithms:

![GtkHash_v1 4](https://user-images.githubusercontent.com/26058215/92444600-cedd2800-f1bb-11ea-9731-b287457400d0.png)

**Comment by tristanheaven** [comment]
I'd prefer not to add other HMACs unless they have been defined somewhere else. For example, the HMAC-RIPEMD160 implementation in gtkhash can be verified using the test cases from [RFC 2286](https://tools.ietf.org/html/rfc2286.html).

**Comment by Ricky-Tigg** [comment]
Hey. Standards rule indeed everything; So hash functions currently having HMAC constructs have then previously been approved as eligible as such by the IETF organisation. Does this mean in your opinion that not all hash functions are meant to have valid HMAC constructs? As the report is labelled _enhancement_, those ideas came to me:

- The program is depicted in Help section as follows,  An explicit term, then _HMAC_, would inform that it does compute HMACs as well.

![GtkHash_1 4_Help](https://user-images.githubusercontent.com/26058215/93078513-46ff8e00-f693-11ea-93ae-8abc01345544.png)

In Preferences section
- As guidance for novices, adding a check-box covering the selection of hash functions that produce valid HMAC constructs.

- A color code ahead each hashing algorithms names who have been weakened enough in strength to raise security concerns, such ones are till now **MD5** and **SHA1** in TLS 1.2 ([Deprecating MD5 and SHA1 in TLS 1.2](https://tools.ietf.org/html/draft-lvelvindron-tls-md5-sha1-deprecate-00)).

**Comment by tristanheaven** [comment]
I don't mean it has to be a standard HMAC. It is possible to enable for any algorithm. The only information needed is the "correct" block size for each one. It's important to get that right because it affects the output, and it wouldn't be very useful if that was different to other applications.
