### ISSUE TITLE
Nautilus extension | Description

### ISSUE THREAD

**Issue by Ricky-Tigg** [tristanheaven/gtkhash#91]
**Component**: gtkhash-nautilus.x86_64 1.4

![extension_gtkhash-nautilus_1 4-2_Title_Checksums](https://user-images.githubusercontent.com/26058215/97012176-425ead00-1550-11eb-82e2-cec11b668adc.png)

```
$ dnf info gtkhash-nautilus | grep -ve '^$' | tail -n 2
Description  : GtkHash extension for the nautilus file manger. It adds adds an additional tab
             : called "Digests" to the file properties dialog.
$ rpm -qi gtkhash-nautilus | tail -n 3
Description :
GtkHash extension for the nautilus file manger. It adds adds an additional tab
called "Digests" to the file properties dialog.
```
- Correct format is `Description : GtkHash (...)`. All others strings are formatted correctly.
- The sentence could be _GtkHash extension for Gnome's Nautilus file manager which adds a Checksums titled tab to the file properties dialogue._

**Comment by tristanheaven** [comment]
The incorrect description comes from the Fedora rpm. Please report the issue to the package maintainer so they can update it there. Thanks.

**Comment by Ricky-Tigg** [comment]
report | [Red Hat Bugzilla](https://bugzilla.redhat.com/show_bug.cgi?id=1891422)
